/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm.estacionamento.apresentacao;

import ihm.estacionamento.aplicacao.Aplicacao;
import ihm.estacionamento.aplicacao.Usuario;

/**
 *
 * @author Rodrigo
 */
public class TelaPrincipal extends javax.swing.JFrame {

    
    TelaLogin telalogin;
    Usuario p;

    public void setTelaLogin(TelaLogin telalogin){
        this.telalogin = telalogin; 
    }
    
    public TelaPrincipal(Usuario p) {
        
        if(!Aplicacao.isLogged()){
            if(telalogin == null)
                telalogin = new TelaLogin();
            
            telalogin.setVisible(true);
            this.setVisible(false);
            this.p = p;
            return;          
        }
        
        initComponents();
        if(p.getTipo().getId() == 2)
            mnuUsuarios.setVisible(false);
    }
    
     public TelaPrincipal() {
        
        if(!Aplicacao.isLogged()){
            if(telalogin == null)
                telalogin = new TelaLogin();
            
            telalogin.setVisible(true);
            this.setVisible(false);
         
            return;          
        }
        
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jdpPrincipal = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        mnuArquivo = new javax.swing.JMenu();
        mnuSair = new javax.swing.JMenuItem();
        mnuUsuarios = new javax.swing.JMenu();
        mnuBuscaUsuario = new javax.swing.JMenuItem();
        mnuClientes = new javax.swing.JMenu();
        mnuClienteFisicoB = new javax.swing.JMenuItem();
        mnuJuridicoB = new javax.swing.JMenuItem();
        mnuVeiculos = new javax.swing.JMenu();
        mnuPagamento = new javax.swing.JMenu();
        mnuSobre = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jdpPrincipal.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jdpPrincipalLayout = new javax.swing.GroupLayout(jdpPrincipal);
        jdpPrincipal.setLayout(jdpPrincipalLayout);
        jdpPrincipalLayout.setHorizontalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 733, Short.MAX_VALUE)
        );
        jdpPrincipalLayout.setVerticalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );

        mnuArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/page.png"))); // NOI18N
        mnuArquivo.setText("Arquivo");

        mnuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sair.png"))); // NOI18N
        mnuSair.setText("Sair");
        mnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairActionPerformed(evt);
            }
        });
        mnuArquivo.add(mnuSair);

        jMenuBar2.add(mnuArquivo);

        mnuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user.png"))); // NOI18N
        mnuUsuarios.setText("Usuarios");
        mnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUsuariosActionPerformed(evt);
            }
        });

        mnuBuscaUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/zoom.png"))); // NOI18N
        mnuBuscaUsuario.setText("Buscar");
        mnuBuscaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBuscaUsuarioActionPerformed(evt);
            }
        });
        mnuUsuarios.add(mnuBuscaUsuario);

        jMenuBar2.add(mnuUsuarios);

        mnuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/clientes (2).png"))); // NOI18N
        mnuClientes.setText("Clientes");

        mnuClienteFisicoB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_gray.png"))); // NOI18N
        mnuClienteFisicoB.setText("Fisico");
        mnuClienteFisicoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClienteFisicoBActionPerformed(evt);
            }
        });
        mnuClientes.add(mnuClienteFisicoB);

        mnuJuridicoB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone-empresa.png"))); // NOI18N
        mnuJuridicoB.setText("Juridico");
        mnuJuridicoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuJuridicoBActionPerformed(evt);
            }
        });
        mnuClientes.add(mnuJuridicoB);

        jMenuBar2.add(mnuClientes);

        mnuVeiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/car.png"))); // NOI18N
        mnuVeiculos.setText("Veiculos");
        jMenuBar2.add(mnuVeiculos);

        mnuPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/money_add.png"))); // NOI18N
        mnuPagamento.setText("Receitas");
        jMenuBar2.add(mnuPagamento);

        mnuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/information.png"))); // NOI18N
        mnuSobre.setText("Sobre");
        jMenuBar2.add(mnuSobre);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed
        telalogin = new TelaLogin();
            
            telalogin.setVisible(true);
            this.setVisible(false);
            this.p = p;
            return;
    }//GEN-LAST:event_mnuSairActionPerformed

    private void mnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuUsuariosActionPerformed

    private void mnuBuscaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBuscaUsuarioActionPerformed
        UsuarioBuscar tela = new UsuarioBuscar(Repositorios.getUsuarioRepositorio(), UsuarioEditar.class);

        jdpPrincipal.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_mnuBuscaUsuarioActionPerformed

    private void mnuClienteFisicoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClienteFisicoBActionPerformed
        ClienteFisicoBuscar tela = new ClienteFisicoBuscar(Repositorios.getFisicoRepositorio(),FisicoEditar.class);
        jdpPrincipal.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_mnuClienteFisicoBActionPerformed

    private void mnuJuridicoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuJuridicoBActionPerformed
        ClienteJuridicoBuscar tela = new ClienteJuridicoBuscar(Repositorios.getJuridicoRepositorio(), JuridicoEditar.class);
        jdpPrincipal.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_mnuJuridicoBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JDesktopPane jdpPrincipal;
    private javax.swing.JMenu mnuArquivo;
    private javax.swing.JMenuItem mnuBuscaUsuario;
    private javax.swing.JMenuItem mnuClienteFisicoB;
    private javax.swing.JMenu mnuClientes;
    private javax.swing.JMenuItem mnuJuridicoB;
    private javax.swing.JMenu mnuPagamento;
    private javax.swing.JMenuItem mnuSair;
    private javax.swing.JMenu mnuSobre;
    private javax.swing.JMenu mnuUsuarios;
    private javax.swing.JMenu mnuVeiculos;
    // End of variables declaration//GEN-END:variables
}
